project_name: 'spryker_docker_sdk'

modules:
  SharedServices:
    path: 'shared_services'
  ProjectManager:
    path: 'project_manager'
  Docker:
    path: 'docker'
#  Ssl:
#    path: './modules/ssl'

shared_services:
    - 'broker'
    - 'dashboard'
    - 'database'
    - 'key_value_store'
    - 'kibana'
    - 'mail_catcher'
    - 'redis-gui'
    - 'scheduler'
    - 'search'
    - 'session'

docker:
  networks:
    - ${project_name}_public
    - ${project_name}_private
